### ISSUE TITLE
Need to upgrade to tocasUI 4.2.4 and change the usage of "space."

### ISSUE THREAD

**Issue by KageRyo** [rumamitw01/MyWebsite#2]
## Tocas 4.2.4 [Latest](https://github.com/teacat/tocas/releases/latest)
> ⚠️ 破壞性異動 ⚠️

> 
> 這些破壞性異動仍可以繼續在 4.2.4 版本中正常使用，但在未來的版本可能隨時都會被移除，請盡快改為新用法。這些樣式被移至 /src/deprecated_423.css 跟 /src/deprecated_430.css。

> 
> [Row] Row 元件被廢除，請改用 Grid (https://github.com/teacat/tocas/issues/913, https://github.com/teacat/tocas/commit/93b757d8858cfaffbaed2f63ee696b2bd0055fea)。
> [Spaced] Space 元件被廢除，請改用輔助樣式的 u-spaced 與 u-padded (https://github.com/teacat/tocas/issues/914, https://github.com/teacat/tocas/commit/93b757d8858cfaffbaed2f63ee696b2bd0055fea)。
> ...

**Comment by rumamitw01** [comment]
Replacement completed
